#aws IAM
cloud:
  aws:
    credentials:
      access-key: ENC(4XpkAQNr5IdK8835BaE496J+loJCmmyV34/qWr1pQcM=)
      secret-key: ENC(WKEyenQg7kETZqdD5o0JYghsJ+98vzVxsDtv4Ck0b4w+m9sZWM4LCwwoAJ0NsTZAtEvicu8WLSk=)
    s3:
      bucket: ENC(YM2F5yiYGgLTLuYGrAQX0leh7G/BodhnwVFmNo68L2Y=)
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  # 데이터베이스 설정
  datasource:
    url: ENC(So3nt33TFOF29VezCsh1qKLxjBRL2BwS3RgGIUdccOi8gLqapC7C3XF3uPxALzs7v2GGaM2fE6atFhbJ+Qt7d+fEEdRPnQRJ53HQQLtURjUf19fztJ+i9w2oGExguKizAbt05P8Jqes=)
    username: ENC(DxYftrrTOw7eRdl4KbaNKvJl+jPCIpm6)
    password: ENC(Kc34HZVf125d2wuW8wXEMBwe8wmRoy3X)
  jpa:
    hibernate:
      ddl-auto: update

  # 소셜로그인 (구글)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(UA1wBmLxiptk40E/ZtKrHnP+v65oez66l/ouFbmsS4VhRISrTjpw7Pfbo2y13OibzXtxktVkj8excxpgCbetURkh4K8nMH8dbKoQhTQk1QgfKXizhXPMPg==)
            client-secret: ENC(FVWByIkYScjOTg31GRAehncmtGo7KoLY7yvVHdzsS9NVt1jrTMYcsyyvArF2GdIS)
            scope: profile,email,openid

  # 이미지 파일 용량 리사이징
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 암호화
jasypt:
  encryptor:
    bean: jasyptStringEncryptor