cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false


spring:
  datasource:
    url:
    username:
    password:

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile,email,openid

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging-module:
  version: 0.0.2


